# -*- coding: utf-8 -*-
"""Trader_Performance_vs_Sentiment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bm0USkMOoCmxpM4dQrn4rWhoDYKmSsuD
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sentiment = pd.read_csv("fear_greed_index.csv")
trades = pd.read_csv("historical_data.csv")

sentiment.head()
trades.head()

sentiment.info()
trades.info()

sentiment.isna().sum()
trades.isna().sum()

sentiment.duplicated().sum()
trades.duplicated().sum()

sentiment["date"] = pd.to_datetime(sentiment["date"])

sentiment.info()

trades["Timestamp IST"] = pd.to_datetime(trades["Timestamp IST"],
dayfirst=True )

trades.info()

trades["Timestamp IST"].tail(10)

trades["date"] = trades["Timestamp IST"].dt.date
trades["date"] = pd.to_datetime(trades["date"])

print(trades["date"].dtype)
print(sentiment["date"].dtype)

trades["date"] = trades["Timestamp IST"].dt.floor("D")

df = trades.merge(
    sentiment[["date", "classification", "value"]],
    on="date",
    how="left"
)

print(df.shape)
print(df["classification"].isna().sum())

"""step-5      BASIC FEATURE ENGINEERING"""

df["win"] = df["Closed PnL"] > 0

df["Direction"] = df["Direction"].str.lower()

daily_pnl = df.groupby(["date","classification"])["Closed PnL"].sum().reset_index()

daily_winrate = df.groupby(["date","classification"])["win"].mean().reset_index()

daily_trades = df.groupby(["date","classification"]).size().reset_index(name="trade_count")

daily_size = df.groupby(["date","classification"])["Size USD"].mean().reset_index()

df.groupby("classification")["Closed PnL"].describe()

df.groupby("classification")["win"].mean()

df.groupby("classification")["Size USD"].mean()

plt.figure()
sns.boxplot(x="classification", y="Closed PnL", data=df)
plt.title("PnL Distribution: Fear vs Greed")
plt.show()

plt.figure()
df.groupby("classification")["win"].mean().plot(kind="bar")
plt.title("Win Rate: Fear vs Greed")
plt.ylabel("Win Rate")
plt.show()

account_trade_count = df.groupby("Account").size()

threshold = account_trade_count.median()

df["trader_type"] = df["Account"].map(
    lambda x: "High Frequency" if account_trade_count[x] > threshold else "Low Frequency"
)

df.groupby(["trader_type","classification"])["Closed PnL"].mean()

size_threshold = df["Size USD"].median()

df["size_group"] = np.where(
    df["Size USD"] > size_threshold,
    "Large Trade",
    "Small Trade"
)

df.groupby(["size_group","classification"])["Closed PnL"].mean()

long_short = df.groupby(["classification","Direction"]).size().unstack()
print(long_short)

df[["Closed PnL","Size USD","value"]].corr()

plt.figure()
sns.boxplot(x="classification", y="Closed PnL", data=df)
plt.title("PnL Distribution by Market Sentiment")
plt.xticks(rotation=45)
plt.show()

df.groupby("classification")["win"].mean()

plt.figure()
df.groupby("classification")["win"].mean().plot(kind="bar")
plt.title("Win Rate by Market Sentiment")
plt.ylabel("Win Rate")
plt.xticks(rotation=45)
plt.show()

long_short = df.groupby(["classification","Direction"]).size().unstack()

long_short.plot(kind="bar")
plt.title("Long vs Short Distribution by Market Sentiment")
plt.ylabel("Number of Trades")
plt.xticks(rotation=45)
plt.show()

